# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Cassia Jiang
title: Creative Developer
email: cassiajiang@outlook.com
# email_title: Email (Email title override)
phone:
# phone_title: Phone (Phone title override)
website: https://unclejiang.github.io/cassia-resume
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Feature
download_resume: false
# change_language: en-US

# Social links
twitter_username:
github_username:
stackoverflow_username:
dribbble_username:
facebook_username:
flickr_username:
instagram_username:
linkedin_username:
xing_username:
pinterest_username:
youtube_username:
orcid_username:
googlescholar_username:

# Additional icon links
# additional_links: # linkedin
# - title: Link name
#   icon: fas fa-file-download # (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, there. I'm Cassia Jiang (蒋殊), trying to make fantastic work using 3D web technologies currently, such as HTML Canvas, mixed reality and generative art, etc.
  There are so many fascinating things, and I hope to have more communication and exchanges with you ~

  Here are some things I have learned & applied:
about_skills:
  - title: "Web3D related :"
    content: Three.js, WebGL Shader
  - title: "Front-end Dev :"
    content: HTML, CSS, Javascript, Typescript, React, React Native, Jest
  - title: "Software :"
    content: Adobe Photoshop, Adobe Illustrator, Unity, Blender


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left # left right 
        border: # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Monbox
        link: https://github.com/UncleJiang/monbox
        link_text: https://github.com/UncleJiang/monbox
        quote: >
          Inspired by the "Moncage", different faces of a cube are used as filters, allowing multiple different scenes to be displayed within a single cube.
        description: | # this will include new lines to allow paragraphs
          [![alt text](/images/monbox.png "Monbox Preview"){:class="bordered-image"}](https://unclejiang.github.io/monbox/dist/index.html){:target="_blank"}
      - layout: left # left right 
        border:   # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Desert
        link: https://github.com/UncleJiang/desert
        link_text: https://github.com/UncleJiang/desert
        quote: >
          An immersive web timer that connects fantastical virtual scenes with reality through time.
        description: | # this will include new lines to allow paragraphs
          [![alt text](/images/desert.png "Desert Preview"){:class="bordered-image"}](https://unclejiang.github.io/desert/dist/index.html){:target="_blank"}
  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: 卫盈联信息技术有限公司 （Welab Bank)
        sub_title: Mobile APP Developer
        caption: July 2020 - June 2022
        link: https://www.welab.bank/
        quote:
        description: | # this will include new lines to allow paragraphs
          - Developed and maintained the investment and loan modules from scratch.
          - Achieved an 'A' rating in annual performance evaluations every year.
  - title: Education
    layout: list
    content:
      - layout: left
        title: |
          School of Computer Science and Artificial Intelligence,
          Wuhan University of Technology 
          武汉理工大学
        sub_title: Bachelor's degree in Software Engineering
        caption: September 2016 - June 2020
        link: http://cst.whut.edu.cn/
        quote:
        description: | # this will include new lines to allow paragraphs
          - School Third-class Scholarship（Sep. 2018 - Jun. 2019）
          - Minister of the Organizational Department in Ziqiang Club, a student organization.
  - title: A Little More About Me
    layout: text
    content:
      - text: I like 
        items: "# Illustration, # Anime, # Psychology, # Dog, # Casual_puzzle_game, # Fashion"
        artwork: 
          - image: images/artwork_01.png
          - image: images/artwork_05.png
          - image: images/artwork_02.png
          - image: images/artwork_06.jpg
          - image: images/artwork_03.png
          # - image: images/artwork_04.png
          # - image: images/artwork_07.png
        imgTail: images/profile.png
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
